name: cloudtest

jobs:
  cloudtest:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/1280px-Image_created_with_a_mobile_phone.png'
          destination: 'kevins_sample'

      # Example of using the output
      - id: 'uploaded-files'
        uses: 'foo/bar@v1'
        env:
          file: '${{ steps.upload-file.outputs.uploaded }}'

