name: cloudtest

on:
  workflow_dispatch:

jobs:
  cloudtest:
    runs-on: macos-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: run build
        run: ./gradlew build composeApp:assembleXCFramework

      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - id: 'kmmbridge publish'
        with:
          path: 'composeApp/build/XCFrameworks/debug/composeApp.xcframework'
          destination: 'kevins_sample'

      - name: Publishing
        env:
          GRADLE_OPTS: -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m"
        run: ./gradlew kmmBridgePublish -PENABLE_PUBLISHING=true --no-daemon --info --stacktrace
