name: cloudtest

on:
  workflow_dispatch:

jobs:
  cloudtest:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          workload_identity_provider: ${{ secrets.WORKLOAD_ID_PROVIDER }}

      - id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: '../composeApp/src/commonMain/composeResources/drawable/compose-multiplatform.xml'
          destination: 'kevins_sample'